### PR TITLE
Remove double slashes in path

### LINKED ISSUE #139: NodeFactory fails to create node tree when the path contains double slashes
The API `NodeFactory.FromDirectory` creates an invalid node tree when the disk file system path contains a double slash.

1. Call the method `NodeFactory.FromDirectory` with a path with double slash like `/tmp//oypdxh0j.dkq`
2. Check the tree of the returned node. It will have the children nodes in `/oypdxh0j.dkq/tmp/oypdxh0j.dkq/child1`

**Expected behavior**
The extra nodes `tmp/oypdxh0j.dkq` are not created an instead the returned node contains the children directly.

### PR DESCRIPTION
**Pull request by Kaplas80**
### Description
Fixes bug when calling `NodeFactory.FromDirectory` using a path with double slashes.

### Example
```cs
Node node = NodeFactory.FromDirectory("/tmp//oypdxh0j.dkq", "*", "name", true);
```

Closes #139

### CODE REVIEW

File: src/Yarhl.UnitTests/FileSystem/NodeFactoryTests.cs [hunk 1]
```diff
@@ -541,5 +541,35 @@ public void CreateFromSubstreamWithNullStreamThrowsException()
...
+            string tempDir = Path.Combine(root, child);
+            Directory.CreateDirectory(tempDir);
+
+            string tempFolder = Path.Combine(tempDir, "folder");
+            Assert.That(Directory.CreateDirectory(tempFolder).Exists, Is.True);
+            string tempFile = Path.Combine(tempFolder, "file.txt");
+            File.Create(tempFile).Dispose();
+
+            Node node = NodeFactory.FromDirectory(
+                string.Concat(root, "//", child),
```
Comment (pleonex) [inline src/Yarhl.UnitTests/FileSystem/NodeFactoryTests.cs]: Can you change the `//` by `Path.PathSeparator + Path.PathSeparator`, so we test this issue for Linux and Windows (the CI runs in the three platforms)?

**Review by pleonex — CHANGES_REQUESTED** [review]
Just a small detail to test paths on Windows and Linux

File: src/Yarhl.UnitTests/FileSystem/NodeFactoryTests.cs (hunk 1 above)
Comment (Kaplas80) [reply src/Yarhl.UnitTests/FileSystem/NodeFactoryTests.cs]: Done!

**Review by pleonex — APPROVED** [review]
All good thanks!
